### ISSUE TITLE
ServerNode caught an exception: TypeError: Matcher.normalizeRound: no matches found

### ISSUE THREAD

**Issue by lieuzhenghong** [lieuzhenghong/bee-experiment#1]
In the `send` step of the game sequence, I want players to send their choices to the server. I have written code in `logic.js` that handles this incoming message, saving it to send to the other player in the next step

The problem is that I can't get the player ID of the other player. In line 50 of `logic.js`, the line `other_player = node.game.matcher.getMatchFor(msg.from);` throws an error:

[https://github.com/lieuzhenghong/bee-experiment/blob/master/nodegame-v5.6.0/games_available/communication-game/game/client_types/logic.js](url)

```
// ServerNode caught an exception:
// TypeError: Matcher.normalizeRound: no matches found
```

```javascript
stager.extendStep('send', {
	cb: function() {
		console.log('Send');
		node.on.data('sending_msg', function(msg) {
			// Everything looks good here...
			console.log("message received!");
			console.log(msg)
			console.log(msg.from)
			// [BUG] [TODO]
			// The following line throws an error:
			// ServerNode caught an exception:
			// TypeError: Matcher.normalizeRound: no matches found
			// But it can get the correct ID in msg.from...
			other_player = node.game.matcher.getMatchFor(msg.from);
			console.log(`The other player is: ${other_player}`);
			message_choices = msg.data.message_choices;
		});
	}
});
```

This is very strange, as the same line `observer = node.game.matcher.getMatchFor(msg.from);` in the subsequent `game` step works fine.

**Comment by lieuzhenghong** [comment]
Output from the console in the `send` step: 

```
message received!
GameMsg {
  id: 642869,
  sid: '/communication-game#Vf4LAgsQ8D0Pws8YAAAB',
  session: '1803734328341713',
  stage: { stage: 2, step: 1, round: 1 },
  action: 'say',
  target: 'DATA',
  from: '35803979085094',
  to: '988783818878862',
  text: 'sending_msg',
  data: { message_choices: { communication_choices: [Object] } },
  priority: 0,
  reliable: 1,
  created: '2020-01-04T00:47:19.552Z',
  forward: 0 }
35803979085094
error: ServerNode caught an exception: 
TypeError: Matcher.normalizeRound: no matches found.
    at Matcher.normalizeRound (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/matcher/Matcher.js:793:19)
    at MatcherManager.round2Index (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/matcher/MatcherManager.js:388:34)
    at MatcherManager.getMatchFor (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/matcher/MatcherManager.js:247:29)
    at Game.<anonymous> (/home/lieu/dev/bee_game/nodegame-v5.6.0/games_available/communication-game/game/client_types/logic.js:49:38)
    at Game.<anonymous> (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/listeners/aliases.js:45:43)
    at Game.<anonymous> (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/modules/alias.js:80:26)
    at EventEmitter.emit (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/core/EventEmitter.js:216:31)
    at NodeGameClient.EventEmitterManager.emit (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/core/EventEmitter.js:726:31)
    at Socket.onMessageFull (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/core/Socket.js:564:23)
    at SocketDirect.message (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/sockets/SocketDirect.js:100:26)

message received!
GameMsg {
  id: 717064,
  sid: '/communication-game#yvX_Zlz0l7w4q9DnAAAA',
  session: '1803734328341713',
  stage: { stage: 2, step: 1, round: 1 },
  action: 'say',
  target: 'DATA',
  from: '982291930298290',
  to: '988783818878862',
  text: 'sending_msg',
  data: { message_choices: { communication_choices: [Object] } },
  priority: 0,
  reliable: 1,
  created: '2020-01-04T00:47:25.907Z',
  forward: 0 }
982291930298290
error: ServerNode caught an exception: 
TypeError: Matcher.normalizeRound: no matches found.
    at Matcher.normalizeRound (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/matcher/Matcher.js:793:19)
    at MatcherManager.round2Index (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/matcher/MatcherManager.js:388:34)
    at MatcherManager.getMatchFor (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/matcher/MatcherManager.js:247:29)
    at Game.<anonymous> (/home/lieu/dev/bee_game/nodegame-v5.6.0/games_available/communication-game/game/client_types/logic.js:49:38)
    at Game.<anonymous> (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/listeners/aliases.js:45:43)
    at Game.<anonymous> (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/modules/alias.js:80:26)
    at EventEmitter.emit (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/core/EventEmitter.js:216:31)
    at NodeGameClient.EventEmitterManager.emit (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/core/EventEmitter.js:726:31)
    at Socket.onMessageFull (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/core/Socket.js:564:23)
    at SocketDirect.message (/home/lieu/dev/bee_game/nodegame-v5.6.0/node_modules/nodegame-client/lib/sockets/SocketDirect.js:100:26)

```

And subsequently in the `game` step:

```
Game round: 1
GameMsg {
  id: 641376,
  sid: '/communication-game#yvX_Zlz0l7w4q9DnAAAA',
  session: '1803734328341713',
  stage: { stage: 3, step: 1, round: 1 },
  action: 'set',
  target: 'DATA',
  from: '982291930298290',
  to: '988783818878862',
  text: 'done',
  data: 
   { time: 3092,
     timeup: false,
     offer: 50,
     done: true,
     player: '982291930298290',
     stage: { stage: 3, step: 1, round: 1 },
     timestamp: 1578098854991 },
  priority: 0,
  reliable: 1,
  created: '2020-01-04T00:47:34.989Z',
  forward: 0 }
982291930298290
The other player is: 35803979085094
```

**Comment by shakty** [comment]
Hi Zhenghong,

Thanks for opening this issue. I checked your logic.js file, and the problem is that you are not starting the matcher in the logic _before_ calling the `getMatchFor` method. See [line 77](https://github.com/nodeGame/ultimatum-game/blob/roles/game/client_types/logic.js#L77) of the ultimatum logic.

In the ultimatum example, there also roles which you might not need (not implemented as of now in your game). Just add something like

{
        matcher: {
            match: 'roundrobin'
        }, 

in the same step in logic.js

Here is some background:

The Matcher API allows you to match participants in pairs. If you have a group of 10 participants, you can easily create 5 pairs. If you have just two players in a group, maybe you don't need to use the Matcher API.  

See here: https://github.com/nodeGame/nodegame/wiki/Matching-Roles-Partners-v5
However, it might be a bit technical.

Have a try and let me know.

**Comment by lieuzhenghong** [comment]
Dear Stefano,

Thanks for the reply. I thought that was the case, but I saw your [logic.js file in prisoner's dilemma](https://github.com/shakty/prisonersgame/blob/master/game/client_types/logic.js) and it didn't seem to have a matcher. In any case, I've added that matcher code in the `send` step in `logic.js`, and it works now! Thank you.

I have just two players in a game, but I was thinking whether I should wait for at least four people to join a waiting room before starting---to prevent people from using multiple MTurk accounts? I would like to ask your advice on this --- what is best practice here?

Thank you so much for your help!

**Comment by shakty** [comment]
The prisoner game is not using the matcher API at all, it keeps a local copy of the ids.

About your question, I would recommend to have a larger pool size yes, 4 at least, but recommeded 6 or 8 or even 10. It depends on how many assignments you are going to have if you can have a larger pool size. Having a larger pool size does not prevent people from using multiple Mturk accounts, it just slightly reduces the likelihood that they end up playing together. The biggest advantage, however, is that you create more mixing within the groups. In fact, the first people to connect are usually "professional" turkers, they are a very specific subgroup. This is even more important if you have multiple treatments.
